# title: "My Jekyll Site"
# description: "A site with dark mode"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site

theme: jekyll-theme-midnight

# Enable dark mode
minima:
  skin: dark

# Build settings
# markdown: kramdown
# highlighter: rouge