name: Update ArXiv Cache

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch: {}
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create data directory
        run: mkdir -p data
      
      - name: Fetch ArXiv Data
        run: |
          # Fetch and store raw XML
          curl -s "https://export.arxiv.org/api/query?search_query=all:causal+inference&sortBy=submittedDate&sortOrder=descending&start=0&max_results=10" > data/arxiv-cache.xml
          # Add timestamp as XML comment
          sed -i "1i<!-- Last updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ") -->" data/arxiv-cache.xml

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add data/arxiv-cache.xml
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update ArXiv cache"
            git push origin main
          fi
