name: Update ArXiv Page Timestamp

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:      # Allow manual triggers

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update timestamp
        run: |
          current_time=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i "s/<span id=\"update-time\">.*<\/span>/<span id=\"update-time\">$current_time<\/span>/" course_content/arxiv_causal.md
          
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add course_content/arxiv_causal.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update ArXiv page timestamp" && git push)
