name: Update ArXiv Page Timestamp

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-timestamp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update timestamp
        run: |
          current_time=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          sed -i "s/<span id=\"update-time\">.*<\/span>/<span id=\"update-time\">$current_time<\/span>/" course_content/arxiv_causal.md
          
      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add course_content/arxiv_causal.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update ArXiv page timestamp" && git push)
